name: Deploy workspace

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 2

      - name: Build workspace
        uses: "pagopa/io-std/build-workspace@main"
        with:
          workspace-name: ${{ inputs.workspace-name }}

      - name: Make workspace artifact
        id: make_artifact
        uses: "pagopa/io-std/make-workspace-artifact@main"
        with:
          workspace-name: ${{ inputs.workspace-name }}

      - name: Upload workspace artifact
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          name: ${{ inputs.workspace-name }}
          path: ${{ steps.make_artifact.outputs.artifact-path }}

  deploy:
    name: Deploy
    if: ${{ !github.event.act }}
    needs: [build]
    runs-on: self-hosted
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: ${{ inputs.workspace-name }}

      - name: Login to Azure
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to ${{ vars.AZURE_WEB_APP_NAME }} staging slot
        uses: azure/webapps-deploy@122b7ec46017e53a3f71e3a027d67550a1641f5e # v2
        with:
          resource-group-name: ${{ vars.AZURE_WEB_APP_RESOURCE_GROUP }}
          app-name: ${{ vars.AZURE_WEB_APP_NAME }}
          slot-name: staging
          package: ${{ inputs.workspace-name }}.zip

      - name: Check staging health
        run: curl --retry 5 --retry-max-time 120 --retry-all-errors -f 'https://${{ vars.AZURE_WEB_APP_NAME }}-staging.azurewebsites.net${{ vars.HEALTH_CHECK_PATH }}'

      - name: Swap staging slot with production
        run: az webapp deployment slot swap -g ${{ vars.AZURE_WEB_APP_RESOURCE_GROUP }} -n ${{ vars.AZURE_WEB_APP_NAME }} --slot staging --target-slot production
